import { Inter } from "next/font/google";
import "./globals.css";

const fontInter = Inter ({
  subsets : ["latin"],
  weight : ["400", "500", "600", "700"]
})

export const metadata = {
  title: "Pokedex",
  description: "Generated by Tim PKL",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${fontInter.className } h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
